/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ComptrollerErrorReporter,
  ComptrollerErrorReporterInterface,
} from "../ComptrollerErrorReporter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256",
      },
    ],
    name: "Failure",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122020730de74f036b1d20f1336b7a974fb5a6b6aa4d597fdf163dcdad04542038e364736f6c634300080a0033";

export class ComptrollerErrorReporter__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ComptrollerErrorReporter> {
    return super.deploy(overrides || {}) as Promise<ComptrollerErrorReporter>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ComptrollerErrorReporter {
    return super.attach(address) as ComptrollerErrorReporter;
  }
  connect(signer: Signer): ComptrollerErrorReporter__factory {
    return super.connect(signer) as ComptrollerErrorReporter__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ComptrollerErrorReporterInterface {
    return new utils.Interface(_abi) as ComptrollerErrorReporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ComptrollerErrorReporter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ComptrollerErrorReporter;
  }
}
