/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { DaiJoinLike, DaiJoinLikeInterface } from "../DaiJoinLike";

const _abi = [
  {
    inputs: [],
    name: "dai",
    outputs: [
      {
        internalType: "contract GemLike",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "vat",
    outputs: [
      {
        internalType: "contract VatLike",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class DaiJoinLike__factory {
  static readonly abi = _abi;
  static createInterface(): DaiJoinLikeInterface {
    return new utils.Interface(_abi) as DaiJoinLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DaiJoinLike {
    return new Contract(address, _abi, signerOrProvider) as DaiJoinLike;
  }
}
