/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { GlpManager, GlpManagerInterface } from "../GlpManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "maximise",
        type: "bool",
      },
    ],
    name: "getAumInUsdg",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class GlpManager__factory {
  static readonly abi = _abi;
  static createInterface(): GlpManagerInterface {
    return new utils.Interface(_abi) as GlpManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GlpManager {
    return new Contract(address, _abi, signerOrProvider) as GlpManager;
  }
}
