/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { JugLike, JugLikeInterface } from "../JugLike";

const _abi = [
  {
    inputs: [],
    name: "base",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "ilks",
    outputs: [
      {
        internalType: "uint256",
        name: "duty",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rho",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060d88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80635001f3b5146037578063d9638d36146052575b600080fd5b603f60015481565b6040519081526020015b60405180910390f35b6076605d366004608a565b6000602081905290815260409020805460019091015482565b604080519283526020830191909152016049565b600060208284031215609b57600080fd5b503591905056fea2646970667358221220643bcdd35930f270bed79011e047a25efada94dc6da576b6af1e79204f48985f64736f6c634300080a0033";

export class JugLike__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<JugLike> {
    return super.deploy(overrides || {}) as Promise<JugLike>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): JugLike {
    return super.attach(address) as JugLike;
  }
  connect(signer: Signer): JugLike__factory {
    return super.connect(signer) as JugLike__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): JugLikeInterface {
    return new utils.Interface(_abi) as JugLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JugLike {
    return new Contract(address, _abi, signerOrProvider) as JugLike;
  }
}
