/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Maximillion, MaximillionInterface } from "../Maximillion";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract CEther",
        name: "cEther_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "cEther",
    outputs: [
      {
        internalType: "contract CEther",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "repayBehalf",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        internalType: "contract CEther",
        name: "cEther_",
        type: "address",
      },
    ],
    name: "repayBehalfExplicit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103b33803806103b383398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b610320806100936000396000f3fe6080604052600436106100345760003560e01c806319b68c0014610039578063367b7f05146100755780639f35c3d51461008a575b600080fd5b34801561004557600080fd5b50600054610059906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61008861008336600461024f565b61009d565b005b610088610098366004610288565b610220565b6040516305eff7ef60e21b81526001600160a01b03838116600483015234916000918416906317bfdfbc906024016020604051808303816000875af11580156100ea573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061010e91906102ac565b9050808211156101bc5760405163e597461960e01b81526001600160a01b03858116600483015284169063e59746199083906024016000604051808303818588803b15801561015c57600080fd5b505af1158015610170573d6000803e3d6000fd5b5050505050336001600160a01b03166108fc828461018e91906102c5565b6040518115909202916000818181858888f193505050501580156101b6573d6000803e3d6000fd5b5061021a565b60405163e597461960e01b81526001600160a01b03858116600483015284169063e59746199084906024016000604051808303818588803b15801561020057600080fd5b505af1158015610214573d6000803e3d6000fd5b50505050505b50505050565b6000546102379082906001600160a01b031661009d565b50565b6001600160a01b038116811461023757600080fd5b6000806040838503121561026257600080fd5b823561026d8161023a565b9150602083013561027d8161023a565b809150509250929050565b60006020828403121561029a57600080fd5b81356102a58161023a565b9392505050565b6000602082840312156102be57600080fd5b5051919050565b6000828210156102e557634e487b7160e01b600052601160045260246000fd5b50039056fea26469706673582212203525d947b9a2e9ce059169dfdd339fd7055a55f68f35d177b802a16cc785c3a564736f6c634300080a0033";

export class Maximillion__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    cEther_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Maximillion> {
    return super.deploy(cEther_, overrides || {}) as Promise<Maximillion>;
  }
  getDeployTransaction(
    cEther_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(cEther_, overrides || {});
  }
  attach(address: string): Maximillion {
    return super.attach(address) as Maximillion;
  }
  connect(signer: Signer): Maximillion__factory {
    return super.connect(signer) as Maximillion__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaximillionInterface {
    return new utils.Interface(_abi) as MaximillionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Maximillion {
    return new Contract(address, _abi, signerOrProvider) as Maximillion;
  }
}
