version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  test:
    docker:
      - image: cimg/node:16.17.1
    working_directory: ~/repo
    steps:
      - run: |
          sudo wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux -O /usr/local/bin/solc
          sudo chmod +x /usr/local/bin/solc
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - v3-scenario/dependencies-{{ checksum "scenario/yarn.lock" }}
      - restore_cache:
          keys:
            - v3-solcache
      - restore_cache:
          keys:
            - v3-scencache
      - run: yarn install || (yarn cache clean && yarn install)
      - run: cd node_modules/@compound-finance/sol-tracing-utils && yarn install
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn install
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn run build || true
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn run copy-files
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && mv dist/Solidity-EZVQ6AE4.tokens dist/Solidity.tokens
      - run: cd scenario && (yarn install || (yarn cache clean && yarn install))
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - scenario/node_modules
          key: v3-scenario-dependencies-{{ checksum "scenario/yarn.lock" }}
      - attach_workspace:
          at: ~/repo
      - run:
          command: npx hardhat node:test
          background: true
      - run:
          command: npx hardhat test tender/test/Erc20.ts
      - run: mkdir ~/junit
      - run: ./script/build_scenarios
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 12.16.2
            nvm alias default 12.16.2

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          shell: /bin/bash -eox pipefail -O globstar
          name: yarn test
          command: NODE_OPTIONS="--max-old-space-size=12228" JEST_JUNIT_OUTPUT_DIR=~/junit JEST_JUNIT_OUTPUT_NAME=test-results.xml yarn test $(circleci tests glob 'tests/**/**Test.js' | circleci tests split --split-by=timings)
      - save_cache:
          paths:
            - .build
            - .solcache
          key: v3-solcache
      - save_cache:
          paths:
            - scenario/.tsbuilt
            - .scencache
          key: v3-scencache
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
    parallelism: 3
    resource_class: xlarge

  verify:
    docker:
      - image: compoundfinance/alpine-java-z3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: script/verify
    parallelism: 4

  coverage:
    docker:
      - image: cimg/node:16.17.1
    working_directory: ~/repo
    steps:
      - run: |
          sudo wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux -O /usr/local/bin/solc
          sudo chmod +x /usr/local/bin/solc
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - v3-scenario-dependencies-{{ checksum "scenario/yarn.lock" }}
      - restore_cache:
          keys:
            - v3-solcache
      - restore_cache:
          keys:
            - v3-scencache
      - run: yarn install || (yarn cache clean && yarn install)
      - run: cd node_modules/@compound-finance/sol-tracing-utils && yarn install
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn install
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn run build || true
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && yarn run copy-files
      - run: cd node_modules/@compound-finance/sol-tracing-utils/node_modules/solidity-parser-antlr && mv dist/Solidity-EZVQ6AE4.tokens dist/Solidity.tokens
      - run: cd scenario && (yarn install || (yarn cache clean && yarn install))
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - scenario/node_modules
          key: v2-scenario-dependencies-{{ checksum "scenario/package.json" }}
      - attach_workspace:
          at: ~/repo
      - run: mkdir ~/junit
      - run: ./script/build_scenarios
      - run:
          shell: /bin/bash -eox pipefail -O globstar
          name: yarn test
          no_output_timeout: 30m
          command: NODE_OPTIONS="--max-old-space-size=12228" JEST_JUNIT_OUTPUT_DIR=~/junit JEST_JUNIT_OUTPUT_NAME=test-results.xml script/coverage $(circleci tests glob 'tests/**/**Test.js' | circleci tests split --split-by=timings) -- --maxWorkers=4
      - save_cache:
          paths:
            - .build
            - .solcachecov
          key: v3-solcache
      - save_cache:
          paths:
            - scenario/.tsbuilt
            - .scencache
          key: v3-scencache
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/repo/coverage/coverage-final.json
          destination: coverage-final.json
      - store_artifacts:
          path: ~/repo/coverage/lcov-report
          destination: coverage
      - codecov/upload:
          file: ~/repo/coverage/coverage-final.json
    parallelism: 10
    resource_class: xlarge

  lint:
    docker:
      - image: cimg/node:18.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install || (yarn cache clean && yarn install)
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ~/repo
      - run: yarn run lint

  docker:
    docker:
      - image: cimg/go:1.13
    steps:
      - run: |
          if [ -z "$DOCKER_USER" -o -z "$DOCKER_PASS" -o -z "$DOCKER_REPO" ]; then
            echo "No DOCKER_REPO, DOCKER_USER or DOCKER_PASS, skipping Docker build..."
            circleci-agent step halt
          fi
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

          set -x

          IMAGE_NAME=${CIRCLE_PROJECT_USERNAME/-/}/$CIRCLE_PROJECT_REPONAME
          COMMIT_TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$COMMIT_TAG .
          docker push $IMAGE_NAME:$COMMIT_TAG

          if [ -n "$CIRCLE_TAG" ]; then
            docker build -t $IMAGE_NAME:$CIRCLE_TAG .
            docker push $IMAGE_NAME:$CIRCLE_TAG
          fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - coverage
      - lint
      - verify
      - docker:
          filters:
            tags:
              only: /^v.*/
