#!/bin/bash

set -eo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
root_dir="$(cd $dir/.. && pwd)"
tests_dir="$(cd $root_dir/tests && pwd)"
scenario_dir="$tests_dir/scenarios"
cache_file="$root_dir/.scencache"
checksum="$(echo $root_dir/spec/scenario/*.scen | xargs shasum -p | shasum -p | cut -d' ' -f 1)"

if [ -z "$rebuild" -a -f "$cache_file" ]; then
  cached="$(cat $cache_file)"

  if [ "$cached" == "$checksum" ]; then
    echo "Skipping Scenario Stub Rebuild (set rebuild=true to force)"
    exit 0
  fi
fi

echo "Build scenario stubs..."
rm -rf "$scenario_dir" && mkdir "$scenario_dir"

scenario_test="$(cat <<-EOF
const scenario = require('../Scenario');

scenario.run('SCEN_FILE');
EOF
)"

for scenario in $root_dir/spec/scenario/*.scen; do
  base="$(basename -- $scenario)"
  filename="${base%.*}ScenTest.js"
  final="$scenario_dir/$filename"
  echo "$scenario_test" | sed "s^SCEN_FILE^$base^g" > "$final"
done

echo "$checksum" > "$cache_file"
