#!/usr/bin/env sh

DIR=`dirname $0`
PROJ_ROOT="$DIR/.."
export BUILD_DIRECTORY="$PROJ_ROOT/.build-temp"
export NETWORK=${1:-development}
export NETWORK_ID=$(npx truffle exec script/javascript/networkId.js --network "$NETWORK" 3>&2 2>&1 1>&3 3>&-)

rm -rf $BUILD_DIRECTORY
node "$DIR/javascript/buildTruffle.js"
npx truffle console --network "$NETWORK"
