#!/usr/bin/env bash

dir=`dirname $0`
proj_root="$dir/.."

export NETWORK="coverage"
case $1 in
    "mocha")
        export SCENARIOS="skipall"
        export NO_TSC="true"
        export no_compile="true" # mocha doesnt need contracts written to by solc
        source $dir/test
        ;;
    "scenario")
        # dont instrument unitroller, slows everything down bigly
        export SKIP_UNITROLLER="true"
        source $dir/test --file="test/ScenarioTest.js"
	      ;;
	  *)
        echo "must provide mocha/scenario option to coverage script"
	      ;;
esac
