#!/usr/bin/env bash

dir=`dirname $0`
proj_root="$dir/.."

node "$proj_root/node_modules/ethereumjs-testrpc-sc/cli.js" \
	--port 8555 \
	--gasLimit 17592186044415 \
	--gasPrice 1 \
	--allowUnlimitedContractSize \
	$@
