#!/bin/bash

set -eo pipefail

DIR=`dirname $0`
PROJ_ROOT="$DIR/.."

"$PROJ_ROOT/node_modules/.bin/solium" -d "$PROJ_ROOT/tests"
"$PROJ_ROOT/node_modules/.bin/solium" -d "$PROJ_ROOT/contracts"
"$PROJ_ROOT/node_modules/.bin/eslint" "$PROJ_ROOT/tests/**/**.js" --fix
"$PROJ_ROOT/node_modules/.bin/eslint" "$PROJ_ROOT/deployment/" --fix
