#!/usr/bin/env bash

set -eo pipefail

dir=`dirname $0`
proj_root="$dir/.."
test_root="$dir/../tests"
contracts_root="$dir/../contracts"
network=${NETWORK:-test}
verbose=${verbose:-}

# Compile scenario runner
[[ -z $NO_TSC ]] && "$proj_root/scenario/script/tsc"

# Build scenario stubs
[[ -z $NO_BUILD_STUB ]] && "$proj_root/script/compile"

# Build scenario stubs
[[ -z $NO_BUILD_SCEN ]] && "$proj_root/script/build_scenarios"

proj_root="$proj_root" verbose="$verbose" npx saddle test $@
